print: ./print.c
	gcc -Wall print.c ../src/*.c -I../include -o print.exe 

base: ./base.c
	gcc -Wall base.c ../src/*.c -I../include -o base.exe 

optimized: ./optimized.c
	gcc -Wall optimized.c ../src/*.c -I../include -o optimized.exe 

recursive_int: ./recursive_int.c
	gcc -Wall recursive_int.c ../src/*.c -I../include -o recursive_int.exe 